### ISSUE TITLE
Write up code of conduct

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/covid_reddit_behaviour#1]
At minimum, we believe that a good/effective code of conduct should include:

- A Statement on diversity and inclusivity
- Details on expected, and unacceptable behaviour
- A list of consequences for unacceptable behaviour
- A procedure for reporting and dealing with unacceptable behaviour

**Comment by LukeAC** [comment]
[CODE_OF_CONDUCT.md](https://github.com/UBC-MDS/DSCI_522_group20/files/7560655/CODE_OF_CONDUCT.md)
Waiting to push this guy to this branch - lacking permissions to push to remote branch at the moment though. Hopefully will have resolved soon...
