### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/covid_reddit_behaviour#20]
@MaeveShi or @nobbynguyen are you able to write up more for the readme? 
I think it needs an introduction and summary etc - thanks!

**Comment by MaeveShi** [comment]
I'll take this! update intro and summary to the main branch right?

**Comment by mel-liow** [comment]
yes please!

**Comment by MaeveShi** [comment]
Readme updated! Added summary, data and some links. Deleted intro(thought it might be redundant), briefly summarized the EDA process. Not much to write because we can only get limited information from EDA, feel free to add or amend!

**Comment by LukeAC** [comment]
Thanks for grabbing this guys! Was there a PR associated with this that we can link to this issue?

**Comment by nobbynguyen** [comment]
Thank you Maeve for taking care of this.
