### ISSUE TITLE
Choosing a dataset and an associated question we will answer in this project

### ISSUE THREAD

**Issue by LukeAC** [UBC-MDS/covid_reddit_behaviour#3]
Let's use this thread to confirm/dispute the use of some dataset. Furthermore, this thread can be used to discuss an associated inferential/predictive question we can ask/answer using this dataset for the purposes of this DSCI 522 project.

At the outset of this thread, the dataset under consideration is the [Reddit Mental Health Dataset](https://zenodo.org/record/3941387#.YZbQMtDMI2x)

**Comment by mel-liow** [comment]
Minute meeting notes from Thursday:

https://docs.google.com/document/d/14bPE46Oedtf_o1zt2A_O-5enR1_uSTtyDF1C0fRILx8/edit

**Comment by mel-liow** [comment]
Just a reminder to myself / anyone that we should probably add the dataset citation to the README.
I also think instructions on how to download data should belong in the README.md file too rather than/ as well as the contributing file so I'll make a separate PR later to do this.
