### ISSUE TITLE
Conduct EDA required for Milestone 1

### ISSUE THREAD

**Issue by LukeAC** [UBC-MDS/covid_reddit_behaviour#4]
We'll create a branch off main called EDA from which sub-branches can be created for each of our own individual EDA

**Comment by mel-liow** [comment]
Yeah - just a thought on this, should we also create an `\eda\subreddit` folder where we put all our individual files for each subreddit dataset? We can then place our merged eda file in the folder above in`\eda`

**Comment by LukeAC** [comment]
For sure - could this be organized this way in the `eda` branch? The alternative (I think - correct me if i'm wrong) would be to instantiate this folder structure first in the `eda` branch, cancel the existing PRs, pull the changed directory structure from the updated `eda`, recommit on our local sub-eda branches, reissue PRs. In hindsight we maybe should have instantiated our ideal project dir structure right off the bat :/

**Comment by mel-liow** [comment]
No, we shouldn't have to do the latter.
It's ok for us to all create an /eda folder separately in our branches and put our files in there. As long as the folder name is the same in each of our branches it should put all of our files together when we merge!

**Comment by LukeAC** [comment]
You're totally right! Was running on Friday-brain for a second there haha..

**Comment by nobbynguyen** [comment]
I agree. Thanks.
