### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/covid_reddit_behaviour#47]
Just collating some of the feedback we've received from TA/ analysis review:

- [x] Look to restructure our folders - maybe include `src` folder
- [ ] Add tests to the scripts
- [ ] Clean up milestone 1 EDA - check all EDA cells work + include a summary that compares before and after and trends
- [ ] Rethink our question/conclusion to move away from descriptive analysis
- [ ] Add contact details in contributing.md

I think it would also be good if we could:
- change the path for each script so that we can run it from the /root folder rather than the data/analysis folder etc - this will help when we write the make file.

Are there any other suggestions on what we can do to improve?
@LukeAC @MaeveShi @nobbynguyen

**Comment by LukeAC** [comment]
I think moving all scripts to the `/src` directory (as opposed to the `~/` (project root) makes sense/could be our first priority.

In terms of building tests, I'll have to review what proprietary methods we actually have...I can't think of any off hand outside of script-specific `main()` methods but will take a look.

I think - based on definitions I quickly looked up - I disagree that our question is 'descriptive'.
> Descriptive statistics summarize the characteristics of a data set. Inferential statistics allow you to test a hypothesis or assess whether your data is generalizable to the broader population.

We are not summarizing characteristics of our dataset here; we are testing the hypothesis that the number of explicit references to substance use before/'after' (ahah) covid is different.

**Comment by nobbynguyen** [comment]
I tried to work on the makefile yesterday, just to test how it works, the path of our script does make it difficult to do the makefile. So, moving all scripts to the src directory is a good idea.

**Comment by LukeAC** [comment]
Here's my proposed work-breakdown for this afternoon:
@nobbynguyen Nobby to create /src dir; move scripts to src dir; run scripts end-to-end and verify functionality (I can assist with debugging!)
@MaeveShi Maeve to clean up EDA
@mel-liow Mel to write MakeFile
@LukeAC Luke to create /tests dir; add test script(s) to /tests

Thoughts/comments/concerns?

**Comment by nobbynguyen** [comment]
Just add one small point: I might need to work on the Readme file to revise the steps of running commands?

**Comment by mel-liow** [comment]
@nobbynguyen yes - that should be part of your PR 😊

**Comment by MaeveShi** [comment]
Clean up milestone 1 EDA - check all EDA cells work + include a summary that compares before and after and trends---
not quite understand the "summary": in milestone 1 we performed 15 eda on datasets respectively, the summary would be from a global level or just for each subreddit(1 or 15?)

**Comment by mel-liow** [comment]
@MaeveShi maybe check with Andy in the other issue thread to see if he can expand further?

**Comment by MaeveShi** [comment]
> I would suggest having one global level table comparing the frequency before and after covid. Is there a way to combine the tables?

>I would also suggest adding a brief summary explaining the details and the conclusion from a global level.

not sure if I understand this right---concatenate all data regardless of subreddit and create a huge csv file, then plot the frequency of substance_use_total and add a summary? 
Another question: create a new path for the summary ipynb file or place it inside eda/subreddit?

**Comment by nobbynguyen** [comment]
I have just checked the link to our final report in the README.md file, it is broken. Error 404 File not found.
[https://ubc-mds.github.io/covid_reddit_behaviour/introduction.html]
Since this link is embedded in the peer review issue, would anyone please help to check why the link is broken and how to fix this?

**Comment by mel-liow** [comment]
Thanks Nobby! good catch - I think I know why, i'll add the build files back to the docs folder
